version: '3'
services:
  web:
    build: .
    ports:
      - "50505:50505"
  mysql:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth1
      MYSQL_USER: auth1
      MYSQL_PASSWORD: password